name       : libdbi-drivers
version    : 0.9.0
release    : 1
source     :
    - https://kent.dl.sourceforge.net/project/libdbi-drivers/libdbi-drivers/libdbi-drivers-0.9.0/libdbi-drivers-0.9.0.tar.gz : 43d2eacd573a4faff296fa925dd97fbf2aedbf1ae35c6263478210c61004c854
license    : LGPL-2.1-or-later
component  : programming.devel
summary    : Drivers for the Database Independent Abstraction Layer for C
description: |
    The libdbi-drivers project maintains drivers for the libdbi database abstraction layer written in C. Drivers are distributed seperately from the library itself.
builddeps  :
    - pkgconfig(dbi)
    - pkgconfig(libpq)
    - pkgconfig(mariadb)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-static \
        --with-mysql \
        --with-pgsql \
        --with-sqlite3 \
        --disable-docs
build      : |
    %make
install    : |
    %make_install
